model: 'efficientnet_b1'
pretrained: 1
reset_last_layer: 1
exp_name: "eff_b1_ft_ext_1"
lr: 1e-5 # default is 1e-4
weight_decay: 1e-5 # default is 1e-5
loss: "focal" # cross_entropy, focal
optim: "adamw" # adamw
batch_size: 250
num_workers: 4
seed: 0 # random seed for reproducibility, default is 0
max_epochs: 50
focal_gamma: 2.5 # default is 2.5
focal_alpha: 0.5 # default is 0.5
focal_reduction: 'none' # default is none, mean, sum
augmentation: 1 # 0, 1
lr_scheduler: "plateau" # none, plateau
val_check_interval: 1.0 # default is 1.0